name: update content

on: push

jobs:
  update:
    name: Update content
    runs-on: ubuntu-latest
    steps:
      - name: checkout the site
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: retrieve private data
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          path: __data
          repository: mgwalker/private-data-test
          ref: main
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      - name: move private data into place
        run: |
          rm -rf interviews
          rm -rf questions
          mv __data/* .
      - uses: actions/setup-node@d6e3b5539ed7e5ccd26c3459e26c7c817f4e9068
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - name: move to GitHub pages
        run: |
          rm -rf docs
          mv public docs
      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/workflows/git.sh